from tkinter import *

root = Tk()
root.geometry("100x100")
root.title("Micro Notepad")

text = Text(root, width = 10)
button2 = Button(root)
button2.config(height= 1, width = 2)
button3 = Button(root)
button3.config(height= 1, width = 2)
button4 = Button(root)
button4.config(height= 1, width = 2)
button5 = Button(root)
button5.config(height= 1, width = 2)
button6 = Button(root)
button6.config(height= 1, width = 2)
button7 = Button(root)
button7.config(height= 1, width = 2)

text.pack(expand = True, side = "left")
button2.pack(fill = BOTH, expand = True)
button3.pack(fill = BOTH, expand = True)
button4.pack(fill = BOTH, expand = True)
button5.pack(fill = BOTH, expand = True)
root.mainloop()